### ISSUE TITLE
Typo causes Data Plan to remain in draft

### ISSUE THREAD

**Issue by cpreid** [mParticle/docs#132]
Typo linked below causes the plan to remain in draft. `activated_environmment` should be `activated_environment`.
https://github.com/mParticle/docs/blob/da05eb237a29f8379e20d7b862f1c54f93fa9cd2/src/pages/developers/dataplanning-api/index.md?plain=1#L275

**Comment by MystiBerry** [comment]
typo fixed and should be visible on the site by 8/9/22
