### ISSUE TITLE
Python SDK consent example uses incorrect timestamp

### ISSUE THREAD

**Issue by paulstallard** [mParticle/docs#142]
The timestamp used in the two consent examples is epoch time in seconds, rather than the required ms.

https://github.com/mParticle/docs/blob/185ea00cd40f9485fb6221a026f756ce253eed45/src/pages/developers/server/python/index.md?plain=1#L158

https://github.com/mParticle/docs/blob/185ea00cd40f9485fb6221a026f756ce253eed45/src/pages/developers/server/python/index.md?plain=1#L174

It should be sometime similar to
`gdpr_consent_state.timestamp_unixtime_ms = time.time_ns()//1000000`

**Comment by MystiBerry** [comment]
Thanks for calling this out! We'll update the docs.

**Comment by MystiBerry** [comment]
Fixed! https://docs.mparticle.com/developers/server/python/#gdpr
