### ISSUE TITLE
On iOS, MParticle.sharedInstance().uploadInterval is read only

### ISSUE THREAD

**Issue by natanrolnik** [mParticle/docs#59]
The docs state in [this page](https://docs.mparticle.com/developers/sdk/ios/upload-frequency/):

```swift
MParticle.sharedInstance().uploadInterval = 30
```

However, [this is the definition](https://github.com/mParticle/mparticle-apple-sdk/blob/master/mParticle-Apple-SDK/Include/mParticle.h#L438) of `uploadInterval` in mParticle.h:

```objc
@property (nonatomic, unsafe_unretained, readonly) NSTimeInterval uploadInterval;
```

The docs should be fixed to reflect that this option can be configured in `MParticleOptions`, not in the `MParticle` instance, with the a correspondent code sample.

**Comment by dbmiller1128** [comment]
@samdozor can you review?

**Comment by alexs-mparticle** [comment]
@natanrolnik and @dbmiller1128 We're going to be making this update shortly.

**Comment by alexs-mparticle** [comment]
@natanrolnik I had one of our iOS engineers review this and we've updated the docs to reflect the correct way of handling this.

Please feel free to take a look at the updated [Upload Frequency](https://docs.mparticle.com/developers/sdk/ios/upload-frequency/) documentation and let us know if there's anything else that's unclear.

**Comment by alexs-mparticle** [comment]
Closing this issue as docs have been updated. If there is any further issue, please reopen or create a new issue.
